services:
  web:
    build: .
    container_name: flask-app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web